spring:
  application:
    name: movie-catalog-service
  profiles:
    active: dev

downstream:
  service:
    url:
      gateway: http://
      ratingsDataService: /ratings-data-service/ratingsData/user/
      movieInfoService: /movie-info-service/movies/

server:
  port: 8081

logging:
  level:
    org.springframework.web: TRACE

